tb_adder:
	SIMNAME=adder \
	vsim -c -do run_sim.tcl
tb_matmul_tree:
	SIMNAME=matmul \
	TREE=1 \
	MULT_TB=1 \
	PY=1 \
	vsim -c -do run_sim.tcl
tb_matmul_partitioned: 
	SIMNAME=matmul \
	MULT_TB=1 \
	MODE=1 \
	PY=1 \
	vsim -c -do run_sim.tcl
tb_matmul_seq:
	SIMNAME=matmul \
	MULT_TB=1 \
	MODE=2 \
	PY=1 \
	vsim -c -do run_sim.tcl
tb_syn_tle_tree:
	SIMNAME=syn_tle \
	TREE=1 \
	MULT_TB=1 \
	MODE=1 \
	PY=0 \
	vsim -c -do run_sim.tcl
tb_syn_tle_seq:
	SIMNAME=syn_tle \
	TREE=1 \
	MULT_TB=1 \
	MODE=2 \
	PY=0 \
	vsim -c -do run_sim.tcl
tb_tree_adder:
	SIMNAME=tree_adder \
	vsim -c -do run_sim.tcl
tb_config_tree_adder:
	SIMNAME=config_tree_adder \
	vsim -c -do run_sim.tcl
tb_config_multiplier_2bit:
	SIMNAME=config_multiplier_2bit \
	vsim -c -do run_sim.tcl
tb_config_shiftadder_4bit:
	SIMNAME=config_shiftadder_4bit \
	vsim -c -do run_sim.tcl
tb_config_multiplier_8bit:
	SIMNAME=config_multiplier_8bit \
	vsim -c -do run_sim.tcl
tb_config_adder:
	SIMNAME=config_adder \
	vsim -c -do run_sim.tcl
tb_seq_mult:
	SIMNAME=seq_mult \
	vsim -c -do run_sim.tcl
tb_seq_mult_adder:
	SIMNAME=seq_mult_adder \
	vsim -c -do run_sim.tcl
tb_seq_MAC:
	SIMNAME=seq_MAC \
	vsim -c -do run_sim.tcl